#!/usr/bin/env ts-node

/**
 * Script to generate TypeScript types from OpenAPI schema
 *
 * Usage:
 *   npm run generate:api-types
 *
 * This script fetches the OpenAPI JSON schema from the running API
 * and generates TypeScript types using openapi-typescript.
 */

import * as fs from "fs";
import * as path from "path";
import * as https from "https";
import * as http from "http";
import openapiTS from "openapi-typescript";

const API_URL = process.env.API_URL || "http://localhost:3000";
const OUTPUT_DIR = path.join(__dirname, "../libs/api-client/src/lib/generated");
const SCHEMA_FILE = path.join(OUTPUT_DIR, "openapi.json");
const TYPES_FILE = path.join(OUTPUT_DIR, "types.ts");

async function fetchOpenApiSchema(): Promise<object> {
  return new Promise((resolve, reject) => {
    const url = new URL(`${API_URL}/api/docs-json`);
    const client = url.protocol === "https:" ? https : http;

    console.log(`Fetching OpenAPI schema from ${url.toString()}...`);

    client
      .get(url.toString(), (res) => {
        let data = "";

        res.on("data", (chunk) => {
          data += chunk;
        });

        res.on("end", () => {
          if (res.statusCode !== 200) {
            reject(
              new Error(
                `Failed to fetch OpenAPI schema: ${res.statusCode} ${res.statusMessage}`
              )
            );
            return;
          }

          try {
            const schema = JSON.parse(data);
            resolve(schema);
          } catch (error) {
            reject(new Error(`Failed to parse OpenAPI schema: ${error}`));
          }
        });
      })
      .on("error", (error: NodeJS.ErrnoException) => {
        const errorMessage = error.message || "Unknown error";
        const errorCode = (error as any).code || "";

        if (
          errorCode === "ECONNREFUSED" ||
          errorCode === "ENOTFOUND" ||
          errorMessage.includes("ECONNREFUSED") ||
          errorMessage.includes("connect") ||
          errorMessage.includes("ECONNREFUSED")
        ) {
          reject(
            new Error(
              `Failed to connect to API at ${API_URL}.\n` +
                `Make sure the API is running:\n` +
                `  npm run dev:api\n\n` +
                `Or set a different API URL:\n` +
                `  API_URL=http://localhost:3000 npm run generate:api-types`
            )
          );
        } else {
          reject(
            new Error(
              `Failed to fetch OpenAPI schema from ${API_URL}: ${errorMessage}`
            )
          );
        }
      });
  });
}

async function generateTypeScriptTypes(schema: any): Promise<string> {
  console.log("Generating TypeScript types using openapi-typescript...");

  try {
    // Use the API URL directly - openapi-typescript can fetch from URLs
    const schemaUrl = `${API_URL}/api/docs-json`;

    // Call openapi-typescript - it returns a Promise<string>
    const types = await openapiTS(schemaUrl);

    // Ensure we have a string
    if (typeof types !== "string") {
      console.error("Unexpected return type:", typeof types);
      console.error("Value:", types);
      throw new Error(
        `Expected string from openapi-typescript, got ${typeof types}`
      );
    }

    return types;
  } catch (error) {
    throw new Error(
      `Failed to generate types: ${error instanceof Error ? error.message : String(error)}`
    );
  }
}

async function main() {
  try {
    // Create output directory if it doesn't exist
    if (!fs.existsSync(OUTPUT_DIR)) {
      fs.mkdirSync(OUTPUT_DIR, { recursive: true });
    }

    // Fetch OpenAPI schema
    const schema = await fetchOpenApiSchema();

    // Save raw schema JSON
    fs.writeFileSync(SCHEMA_FILE, JSON.stringify(schema, null, 2));
    console.log(`✓ Saved OpenAPI schema to ${SCHEMA_FILE}`);

    // Generate TypeScript types using openapi-typescript
    const types = await generateTypeScriptTypes(schema);

    // Add header comment
    const header = `// Auto-generated types from OpenAPI schema
// DO NOT EDIT THIS FILE MANUALLY
// Run 'npm run generate:api-types' to regenerate
// Generated using openapi-typescript: https://github.com/drwpow/openapi-typescript

`;

    fs.writeFileSync(TYPES_FILE, header + types);
    console.log(`✓ Generated TypeScript types to ${TYPES_FILE}`);

    console.log("\n✓ Type generation complete!");
    console.log("\nThe generated types are available as:");
    console.log(
      "  import type { paths, components } from '@ichibytes/api-client/lib/generated/types';"
    );
  } catch (error) {
    console.error("\n✗ Error generating types:");
    if (error instanceof Error) {
      console.error(error.message);
    } else {
      console.error(String(error));
    }
    console.error(
      "\nTip: Make sure the API server is running before generating types."
    );
    process.exit(1);
  }
}

main();
